---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install net-tools
    apt:
      name: net-tools
      state: latest

  - name: Install openssh-server
    apt:
      name: openssh-server
      state: latest

  - name: Check if ssh service is running
    command: systemctl status openssh
    ignore_errors: yes

  - name: Check if ssh service is running again
    ansible.builtit.service:
      name: openssh
      state: started

  - name: Install Git
    apt:
      name: git
      state: latest
